config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root to: 'homes#top'
   get '/home/about' => 'homes#about'
   get '/users/logout' => 'devise/sessions#destroy'
    
    resources :users,only: [:show,:index,:edit,:update, :destroy,:index]  do
        resources :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :books, only: [:new, :create, :index, :show, :edit, :destroy,:update] do
        resources :book_comments, only: [:create,:destroy]
        resource :favorite, only: [:create, :destroy]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    def favorited_by?(user)
     favorites.where(user_id: user.id).exists?
    end
    
    validates :title, presence: true
    
    validates :body, presence: true,length: { maximum:200 }


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name:  "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  
  
  
   # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  attachment :profile_image
  
  
  validates :name, presence: true ,length: { minimum: 2,maximum:20 }
  validates :introduction, length: { maximum:50 }
  validates :name, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :authenticate_user!,except: [:top,:about]

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.finda(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comments)
  end
end
# controllerからviewへの情報の受け渡しはなくviewでコメントを記述してcontroller内で
    # 保存管理を行いcontrollerからviewの受け渡しは、必要ない為、インスタンス変数を
    # 使う必要がなくローカル変数での記述である

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(prams[:id])
    @book = Book.new
    @user = User.find_by(id: @book.user.id)
    redirect_to books_url if @book.blank?
    # blank? railsの拡張。nil, "", " ", [], {} のいずれかでTrueを返す。
  end

  def edit
    @book = Book.firnd(params[:id])
    @user = @book.user
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
  end
  
  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/favolites_controller.rb
class FavolitesController < ApplicationController
      before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
        
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
    def create
        current_user.follow(params[:user_id])
        redirect_to request.referer
    end

    def destroy
        current_user.unfollow(params[:user_id])
        redirect_to request.referer
    end

    def followings
        @user = User.find(params[:user_id])
        @users = @user.followings
    end

    def followers
        @user = User.find(params[:user_id])
        @users = @user.followers
    end

    def index
        @user = User.find(params[:user_id])
        @users = @user.followings
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    @book = current_user.books
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def create
    @user = User.new(params[:id])
    @user.user.id = current_user.user.id
    @user.save
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render:edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
  
    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favolites_helper.rb
module FavolitesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "50x50" , fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <div class="favorite-btn<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'books/errors', book:@book %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, size: "100x100", fallback: "no-image-icon.jpg" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td>
            <div class="favorite-btn<%= @book.id %>">
              <%= render 'favorites/favorite', book: @book %>
            </div>
          </td>
          <td>
            <div id="comments-area">
              <%= render "book_comments/book_comment",book: @book,book_comment: @book_comment %>
            </div>
          </td>
          <% if current_user.id == @book.user_id %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
<% if book.favorited_by?(current_user) %>  
   <%= link_to book_favorite_path(book.id), method: :delete, class: 'btn btn-default', remote: true do %>
       ♥<%= book.favorites.count %>
   <% end %>
<% else %>
      <%= link_to book_favorite_path(book.id), method: :post, class: 'btn btn-default', remote: true do %>
         ♡<%= book.favorites.count %>
      <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn<%= @book.id %>").html("<%= j (render 'favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn<%= @book.id %>").html("<%= j (render 'favorite', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h1>Follower Users</h1>
<tr>
 <% if @users.exists? %>
  <th>name</th>
  <th></th>
</tr>
<tbody>
 <% @users.each do |user| %>
 <tr>
  <td><%= user.name %></td>
  <td>フォロー数: <%= user.followings.count %></td>
  <td>フォロワー数: <%= user.followers.count %></td>
  <td><%= link_to "Show", user %></td>
 <tr>
 <% end %>
</tbody>
 <% else %>
  <th>ユーザーはいません</th>
<% end %>

app/views/relationships/followings.html.erb
<h1>Follower Users</h1>
<tr>
 <% if @users.exists? %>
  <th>name</th>
  <th></th>
</tr>
<tbody>
 <% @users.each do |user| %>
 <tr>
  <td><%= user.name %></td>
  <td>フォロー数: <%= user.followings.count %></td>
  <td>フォロワー数: <%= user.followers.count %></td>
  <td><%= link_to "Show", user %></td>
 <tr>
 <% end %>
</tbody>
 <% else %>
  <th>ユーザーはいません</th>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image,size: "50x50", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        
        <td>コメント件数：<%= @book.book_comments.count %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        <% unless current_user == user %>
         <% if current_user.following?(user) %>
           <td><%= link_to "フォロー外す","/users/#{user.id}/relationships/#{user.id}", method: :delete %></td>
         <% else %>
           <td><%= link_to "フォロー", user_relationships_path(user.id), method: :POST %></td>
         <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<footer>
    <div class="container mt-5">
        <div class="row">
            <div class="mx-auto">
            </div>
        </div>
    </div>
</footer>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
             <table class="table">
                 <tbody>
                    <tr>
                      <%= render 'info', user: current_user %>
                    </tr>
                 </tbody>
             </table>
            <h2 class="mt-3">New book</h2>
                <%= render 'books/form', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            <%= render 'users/index',users: @users %>
            </div>
        </div>
    </div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>